### ISSUE TITLE
Duplicate policy definitions found in 2 different folders

### ISSUE THREAD

**Issue by chaoscreater** [anwather/amba-export#25]
Hi,

I noticed that some policy definitions are duplicated in different folders. For example, the policy definition file "deploy_alb_globalbackendavailability_alert.jsonc" is found under Networking and Unknown Category. They are almost the same file, just slightly different contents (things being shifted around).

This wasn't the issue in the old version from 8 months ago.

![image](https://github.com/anwather/amba-export/assets/18227319/badd5c8e-2193-4a45-ab7b-f4a144241df0)

**Comment by anwather** [comment]
Yes - I think this is due to them changing the metadata - they have capitalised the work ````Category``` - which stuffs up our export. Ideally they should fix that - will raise a PR with them

**Comment by anwather** [comment]
https://github.com/Azure/azure-monitor-baseline-alerts/pull/220

**Comment by anwather** [comment]
This should be fixed now
