### ISSUE TITLE
Assignment Alerting-landing-zones duplicate policy call

### ISSUE THREAD

**Issue by 8ast1en** [anwather/amba-export#44]
Hi Guys,

I've recently do the new update of the Alerting AMBA and I find that somes policy duplicate.

![image](https://github.com/user-attachments/assets/0ccfb29f-abe8-4542-9abf-35bc55eeb264)

In fact, we've some duplicate alerting vm, key vault, load balancer ... Should i delete the assignment alerting-landingzone-policySet for resolve this problem ?

Thanks in advance,

**Comment by anwather** [comment]
Ok - looks like they have changed it to give multiple patterns for deployment - if you are using the ALZ structure continue to use the original policy assignments. The "duplicates" simply give a way to deploy policies for that category to a scope - e.g. if you weren't using ALZ and wanted to deploy all the "storage" alerts you could deploy ```alerting-storage-policySet.jsonc```. 

I'll update the readme to reflect this change.

**Comment by 8ast1en** [comment]
For information, I could see that policy set call by the assigment ALZ-Landing-zones is deprecated to this day

![image](https://github.com/user-attachments/assets/8550f1ba-72c5-4490-8781-8a04fadd32b0)

**Comment by anwather** [comment]
Thanks I've removed it from the main branch
