### ISSUE TITLE
Duplicate Policy Definitions

### ISSUE THREAD

**Issue by zaal-io** [anwather/amba-export#46]
The Imported AMBA Policy Definitions contains duplicate Policy Definitions in the folder "Definitions/policyDefinitions/Unknown Category". This will cause the EPAC Build-DeploymentPlans command to fail.

I can create a PR to remove the "Unknown Category" folder with the duplicate Policy Definitions, but I guess they will appear again with the next run of the "Sync Monitor Policies" Actions workflow.

It looks like the issue started after PR #40 or maybe PR #41 , as the "Unknown Category" folder is firstly introduced in the followed up automated PR #42

**Comment by anwather** [comment]
Thanks I've removed those files.
