### ISSUE TITLE
We got a lot of duplicated policyDefinitions files.

### ISSUE THREAD

**Issue by LarsVidingSE** [anwather/amba-export#53]
Hi, 
I am in the process of setting up AMBA with EPAC and just copied all files under the folder Definitions and pasted the under EPAC Defintions folder.
After the adjustment in assignments files and change the ALZMonitorResourceGroupLocation to westeurope for all AMBA policySetDefinitions files.

Our epac-dev-pipeline stopped because there is a lot of duplicated policyDefinitions files from AMBA. 

It seems that all files under the folder [Unknown Category] are duplicated. 
When comparing the files under the folder [Unknown Category] with the corresponding one. It seems that all files in the folder [Unknown Category] have newer version.

Can you explain the purpose of the folder [Unknown Category] and which file shall be deleted? 
Shall all files that are duplicated be replaced with the one under the folder [Unknown Category]?

Thanks in advance
Lars Viding

A screenshot of some of the duplicated files.
![image](https://github.com/user-attachments/assets/6c7f4c92-b772-4c29-9dde-be14d15c8a50)

Check version under Unknown Category for the duplicated file "deploy_ag_applicationgatewaytotaltime_alert.jsonc"
![image](https://github.com/user-attachments/assets/decd8653-14fb-42fc-85b6-a55b128533ef)

Check version under Networking for the duplicated file "deploy_ag_applicationgatewaytotaltime_alert.jsonc"
![image](https://github.com/user-attachments/assets/7fc7e637-b58e-49f5-8c67-6d4430b0a395)

**Comment by anwather** [comment]
Interesting when we do the export it splits these files up due to the different casing on ```Category``` - one is lower case. But as there are two different versions of the policy I'm not sure which one is the correct one. I'll have to manually run the export and see what comes out I think. 1.4.0 looks like the latest.

**Comment by anwather** [comment]
Have run the process and cleaned up the main branch - there shouldn't be any more duplicate files now

**Comment by LarsVidingSE** [comment]
Thanks for your fast response and that you fixed this issue :)
We have now run the epac-dev-pipeline, with no error, thx.
