### ISSUE TITLE
Question: Query is throttled with ResourceHealth Alerts

### ISSUE THREAD

**Issue by 8ast1en** [anwather/amba-export#63]
Hello @anwather,

I hope you are doing well today,

I've few errors with a ResourceHealth alerts, I regularly receive an error message {"title":"Query is throttled","details":"","currentHealthStatus":"Unavailable","previousHealthStatus":"Available","type":"Downtime","cause":"UserInitiated"}

Do you have any idea on this subject?

If you want more details, do not hesitate.

Thanks a lot,

**Comment by anwather** [comment]
Hi - if you are having an issue with one of the policies please raise it on the AMBA project and they can help. https://github.com/Azure/azure-monitor-baseline-alerts
